### ISSUE TITLE
Clock text not rendered

### ISSUE THREAD

**Issue by billgufran** [iamr8/MacType-Profile#2]
![image](https://user-images.githubusercontent.com/36406369/92947156-33350b80-f48a-11ea-878f-35af509e2f83.png)

Hey I notice there's problem with colon symbol on clock (both on app and taskbar). I've checked the glyph but I don't see anything weird with the colon. Do you happen to know what caused this?

**Comment by billgufran** [comment]
Sorry for the trouble. It turns out the issue come from WIn 10 itself and I've found the workaround

**Comment by iamr8** [comment]
Sorry for late answer.

> Sorry for the trouble. It turns out the issue come from WIn 10 itself and I've found the workaround

Can you please describe your workaround. Maybe it be an common issue for some users.
