### ISSUE TITLE
Windows 10 System Tray Clock COLON Issue Workaround

### ISSUE THREAD

**Issue by ninjaeon** [iamr8/MacType-Profile#4]
Solution found at:  https://www.tenforums.com/installation-upgrade/82691-win-10-pro-creators-update-taskbar-clock-anomaly-any-suggestions.html#post1027583

OPEN REGEDIT
Hkey_Current_User\ControlPanel\International

Double click on "sShortTime"
THEN....
Open up Character Map, switch to unicode and SEARCH for "colon"

SELECT the last one that shows up (U+A789: Modifier Letter Colon)

SELECT COPY and then replace the colon in the sShortTime string.

**Comment by iamr8** [comment]
Thanks for your consideration. I will add it into README asap.

**Comment by ninjaeon** [comment]
By the way, I love your MacType guide. I can only hope that Windows 11 does something like this to replace ClearType, although there's no hope for SF font to be a built-in option.  Until then, I will use your guide.   Thank you very much for it!

**Comment by iamr8** [comment]
It's kind of you.
Windows will does its shit always. even in Windows 11.

If you use the SF Fonts those i preferred in Readme, i will suggest you to use latest version of them.
(Download MAC Fonts from here)[https://developer.apple.com/fonts/]

Extract them and Move .otf files to another files ( google it to find out how to do this with .dmg files )

Use a Online font converter website to convert .otf files to .ttf files.
And copy them to windows folders. This is my method.
For example now i don't have any issue with `:` glyph.

**Comment by ninjaeon** [comment]
I'm still on Windows 10.  I updated to the latest version of the SF Fonts from your link and still have the : glyph issue in the clock unless I do the workaround.  I have Windows system font set to "SF Pro Text" (easy way to set system font is using [https://github.com/alcortazzo/Windows-Font-Changer](https://github.com/alcortazzo/Windows-Font-Changer))

**Comment by ninjaeon** [comment]
I upgraded to Windows 11.  The glyph issue in the system tray clock is resolved in Windows 11 without the workaround with SF Fonts *if* you don't use something like "ExplorerPatcher" to switch the taskbar/system tray back to "Windows 10 Taskbar Style".  Otherwise, the glyph issue comes back and you have to use the workaround.
